---
version: '3.6'

services:
  truenas-system-docs-dev:
    container_name: truenas-system-docs-dev
    image: truenas-system-docs:latest-dev
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile.dev
    volumes:
    - ../docs:/app/docs
    - ../icon.png:/app/icon.png
    - ../CONTRIBUTING.md:/app/CONTRIBUTING.md
    - ../index.html:/app/index.html
    - ../LICENCE.md:/app/LICENCE.md
    - ../README.md:/app/README.md
    ports:
    - 6007:3000
    restart: unless-stopped
